### ISSUE TITLE
Exceptions are not handled when using Gunicorn

### ISSUE THREAD

**Issue by AbdManian** [FanapSoft/FANAP-IoT-Core-Platform#1]
Example:
Accessing without valid user-token

> platform      | [2019-01-08 11:19:45,408] ERROR in app: Exception on /deviceData/todevice/DIa209093e488a4372 [POST]
platform      | Traceback (most recent call last):
platform      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
platform      |     rv = self.dispatch_request()
platform      |   File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1799, in dispatch_request
platform      |     return self.view_functions[rule.endpoint](**req.view_args)
platform      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
platform      |     resp = resource(*args, **kwargs)
platform      |   File "/usr/local/lib/python3.7/site-packages/flask/views.py", line 88, in view
platform      |     return self.dispatch_request(*args, **kwargs)
platform      |   File "/usr/local/lib/python3.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
platform      |     resp = meth(*args, **kwargs)
platform      |   File "/app/app/validation/jsoncheck.py", line 94, in wrapper
platform      |     return func(self, *args, data=data, **kwargs)
platform      |   File "/app/app/validation/check_user_token.py", line 14, in wrapper_usertoken
platform      |     raise ApiExp.AccessDenied
platform      | app.exception.exceptions.ApiExp.AccessDenied

**Comment by AbdManian** [comment]
Fixed in 4023e1dd0f33d6a13a1bae2297b37b60cf2d1d4d
